<?php

namespace DoctrineProxies\__CG__\App\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Cpiui extends \App\Entities\Cpiui implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entities\\Cpiui' . "\0" . 'id', '' . "\0" . 'App\\Entities\\Cpiui' . "\0" . 'title', '' . "\0" . 'App\\Entities\\Cpiui' . "\0" . 'description', '' . "\0" . 'App\\Entities\\Cpiui' . "\0" . 'children', '' . "\0" . 'App\\Entities\\Cpiui' . "\0" . 'cptid', 'parent', '' . "\0" . 'App\\Entities\\Cpiui' . "\0" . 'attribute', '' . "\0" . 'App\\Entities\\Cpiui' . "\0" . 'slug', '' . "\0" . 'App\\Entities\\Cpiui' . "\0" . 'cptuiQuestion', '' . "\0" . 'App\\Entities\\Cpiui' . "\0" . 'cptuiDocument', '' . "\0" . 'App\\Entities\\Cpiui' . "\0" . 'isActive', '' . "\0" . 'App\\Entities\\Cpiui' . "\0" . 'createdAt', '' . "\0" . 'App\\Entities\\Cpiui' . "\0" . 'updatedAt', '' . "\0" . 'App\\Entities\\Cpiui' . "\0" . 'featuredimage'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entities\\Cpiui' . "\0" . 'id', '' . "\0" . 'App\\Entities\\Cpiui' . "\0" . 'title', '' . "\0" . 'App\\Entities\\Cpiui' . "\0" . 'description', '' . "\0" . 'App\\Entities\\Cpiui' . "\0" . 'children', '' . "\0" . 'App\\Entities\\Cpiui' . "\0" . 'cptid', 'parent', '' . "\0" . 'App\\Entities\\Cpiui' . "\0" . 'attribute', '' . "\0" . 'App\\Entities\\Cpiui' . "\0" . 'slug', '' . "\0" . 'App\\Entities\\Cpiui' . "\0" . 'cptuiQuestion', '' . "\0" . 'App\\Entities\\Cpiui' . "\0" . 'cptuiDocument', '' . "\0" . 'App\\Entities\\Cpiui' . "\0" . 'isActive', '' . "\0" . 'App\\Entities\\Cpiui' . "\0" . 'createdAt', '' . "\0" . 'App\\Entities\\Cpiui' . "\0" . 'updatedAt', '' . "\0" . 'App\\Entities\\Cpiui' . "\0" . 'featuredimage'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Cpiui $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getParent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParent', []);

        return parent::getParent();
    }

    /**
     * {@inheritDoc}
     */
    public function getChildren()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChildren', []);

        return parent::getChildren();
    }

    /**
     * {@inheritDoc}
     */
    public function getCptid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCptid', []);

        return parent::getCptid();
    }

    /**
     * {@inheritDoc}
     */
    public function setCptid($cptid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCptid', [$cptid]);

        return parent::setCptid($cptid);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getisActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getisActive', []);

        return parent::getisActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsActive($isActive)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsActive', [$isActive]);

        return parent::setIsActive($isActive);
    }

    /**
     * {@inheritDoc}
     */
    public function getFeaturedimg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFeaturedimg', []);

        return parent::getFeaturedimg();
    }

    /**
     * {@inheritDoc}
     */
    public function setFeaturedimg($featuredimg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFeaturedimg', [$featuredimg]);

        return parent::setFeaturedimg($featuredimg);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function addChild(\App\Entities\Cpiui $child)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addChild', [$child]);

        return parent::addChild($child);
    }

    /**
     * {@inheritDoc}
     */
    public function setParent(\App\Entities\Cpiui $parent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParent', [$parent]);

        return parent::setParent($parent);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttribute()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttribute', []);

        return parent::getAttribute();
    }

    /**
     * {@inheritDoc}
     */
    public function setAttribute($attribute)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttribute', [$attribute]);

        return parent::setAttribute($attribute);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', []);

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlug($slug)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlug', [$slug]);

        return parent::setSlug($slug);
    }

    /**
     * {@inheritDoc}
     */
    public function getFeaturedimage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFeaturedimage', []);

        return parent::getFeaturedimage();
    }

    /**
     * {@inheritDoc}
     */
    public function setFeaturedimage($featuredimage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFeaturedimage', [$featuredimage]);

        return parent::setFeaturedimage($featuredimage);
    }

    /**
     * {@inheritDoc}
     */
    public function getCptuiQuestion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCptuiQuestion', []);

        return parent::getCptuiQuestion();
    }

    /**
     * {@inheritDoc}
     */
    public function setCptuiQuestion($cptuiQuestion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCptuiQuestion', [$cptuiQuestion]);

        return parent::setCptuiQuestion($cptuiQuestion);
    }

    /**
     * {@inheritDoc}
     */
    public function getCptuiDocument()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCptuiDocument', []);

        return parent::getCptuiDocument();
    }

    /**
     * {@inheritDoc}
     */
    public function setCptuiDocument($cptuiDocument)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCptuiDocument', [$cptuiDocument]);

        return parent::setCptuiDocument($cptuiDocument);
    }

    /**
     * {@inheritDoc}
     */
    public function addQuestionariesLink(\App\Entities\CptuiQuestionariesLink $cptuiQuestionariesLink)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addQuestionariesLink', [$cptuiQuestionariesLink]);

        return parent::addQuestionariesLink($cptuiQuestionariesLink);
    }

    /**
     * {@inheritDoc}
     */
    public function addDocumentLink(\App\Entities\CptuiDocumentLink $cptuiDocumentLink)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDocumentLink', [$cptuiDocumentLink]);

        return parent::addDocumentLink($cptuiDocumentLink);
    }

}
